name: render-md-mermaid

on:
  push:
    paths:
      - '**.md'

jobs:
  render-md-mermaid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Run Mermaid CLI
        run: |
          npm install -g @mermaid-js/mermaid-cli
          mmdc -i input.mmd -o output.png

      - name: Commit rendered diagrams
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "*[.svg,.png]"
          commit_message: "automatically rendered mermaid diagrams"
